apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - python-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: python-app
        image: vakula2004/python-app:latest
        ports:
        - containerPort: 5000
