apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-python-app-ingress
  namespace: default
  annotations:
    # Важно для новых версий ingress-nginx
    ingressclass.kubernetes.io/is-default-class: "true"
    # Если хочешь заходить просто по IP без домена:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # Добавь эту строку явно
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-python-app-service
            port:
              number: 80
