apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crypto-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-python-app-service  # Имя твоего сервиса
            port:
              number: 80