apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-python-app-ingress
  namespace: default
  annotations:
    # Убираем лишнее, оставляем только нужное для работы путей
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crypto-monitor-service  # <--- ПРАВИЛЬНОЕ ИМЯ
            port:
              number: 5000               # <--- ПРАВИЛЬНЫЙ ПОРТ